---
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    listener_filters:
    - name: envoy.listener.tls_inspector
      config: {}
    filter_chains:
    - filter_chain_match:
        server_names: "*.wikipedia.org"
      filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: wikipedia
          access_log:
          - config:
              path: "/dev/stdout"
              format: "[%START_TIME%] %PROTOCOL% %BYTES_RECEIVED% %BYTES_SENT% %RESPONSE_FLAGS%
                %UPSTREAM_HOST% %UPSTREAM_CLUSTER% %REQUESTED_SERVER_NAME%\n"
            name: envoy.file_access_log
          cluster: second_proxy
    - filter_chain_match:
        server_names: "*.cnn.com"
      filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: cnn
          access_log:
          - config:
              path: "/dev/stdout"
              format: "[%START_TIME%] %PROTOCOL% %BYTES_RECEIVED% %BYTES_SENT% %RESPONSE_FLAGS%
                %UPSTREAM_HOST% %UPSTREAM_CLUSTER% %REQUESTED_SERVER_NAME%\n"
            name: envoy.file_access_log
          cluster: second_proxy
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 15001
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        config:
          cluster: BlackHoleCluster
          stat_prefix: BlackHoleCluster
    use_original_dst: true
  clusters:
  - name: second_proxy
    connect_timeout: 2.5s
    type: STATIC
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 15002
    dns_lookup_family: v4_only
    tlsContext:
      commonTlsContext:
        tlsCertificates:
        - certificateChain:
            filename: "/etc/my-certs/envoy1.crt"
          privateKey:
            filename: "/etc/my-certs/envoy1.key"
        validationContext:
          trustedCa:
            filename: "/etc/my-certs/envoy2.crt"
        alpnProtocols:
        - h2
        - http/1.1
      sni: envoy2.local
  - name: BlackHoleCluster
    connect_timeout: 5.0s
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
